<?php

$lang = array(
    'eng' => array(
        'lang' => 'english',
        'top' => 'Welcome to VertrigoServ',
        'change_lang' => 'Change language',
		'info' => 'Information',
        'left_1' => 'Thanks for using this program and congratulations for your choice!',
		'packages' => 'Packages:',
        'php_ext' => 'Loaded PHP extensions:',
		'mysql_ps' => 'MySQL password status (for root):',
		'mysql_red' => 'You have to change the default MySQL password',
		'mysql_green' => 'The default MySQL password has been changed',
		'tools' => 'Tools and links',
		'local_tools' => 'Local tools:',
		'misc' => 'Miscellaneous:',
		'links' => 'Links:',
		'manuals' => 'Manuals:',
		'view_phpinfo' => 'View phpinfo() screen',
		'view_extensions' => 'View loaded PHP extensions',
		'apache_info' => 'Apache Server Information',
		'homepage' => 'VertrigoServ Project Page',
    ),
    'pl' => array(
        'lang' => 'polski',
        'top' => 'Witaj w VertrigoServ',
        'change_lang' => 'Zmie&#324 j&#281zyk',
		'info' => 'Informacje',
        'left_1' => 'Gratuluj&#281 wybrania VertrigoServ i zapraszam do korzystania oraz tworzenia aplikacji bazodanowych z wykorzystaniem VertrigoServ!',
	    'packages' => 'Komponenety:',
	    'php_ext' => 'Za&#322adowane rozszerzenia PHP:',
        'mysql_ps' => 'Stan has&#322a MySQL (dla roota):',
		'mysql_red' => 'Domy&#347lne has&#322o MySQL nie zosta&#322o zmienione',
		'mysql_green' => 'Domy&#347lne has&#322o MySQL zosta&#322o zmienione',
		'tools' => 'Narz&#281dzia i linki',
		'local_tools' => 'Lokalne narz&#281dzia:',		
		'misc' => 'R&#243&#380no&#347ci:',
		'links' => 'Linki:',
		'manuals' => 'Manuale:',
		'view_phpinfo' => 'Zobacz stron&#281 phpinfo()',
		'view_extensions' => 'Zobacz za&#322adowane rozszerzenia PHP',
		'apache_info' => 'Informacje o serwerze Apache',
		'homepage' => 'Strona projektu VertrigoServ',
    ),
);

?>